import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: ["./index.html", "./src/**/*.{ts,tsx}"],
  theme: {
    extend: {
      colors: {
        "primary-fixed": "#5ea2ff",
        "on-background": "#2d2f2f",
        "inverse-surface": "#0c0f0f",
        "surface-container-highest": "#dbdddd",
        surface: "#f6f6f6",
        "error-container": "#fb5151",
        "on-error": "#ffefee",
        "on-surface-variant": "#5a5c5c",
        outline: "#767777",
        "surface-bright": "#f6f6f6",
        "on-secondary-fixed": "#443700",
        primary: "#005bad",
        "secondary-fixed-dim": "#edc600",
        "on-surface": "#2d2f2f",
        "tertiary-fixed": "#ff9285",
        "inverse-primary": "#4194fb",
        "surface-container-high": "#e1e3e3",
        "on-tertiary-fixed-variant": "#7a0004",
        "on-tertiary": "#ffefed",
        "secondary-container": "#fed400",
        "on-secondary-fixed-variant": "#655300",
        "tertiary-fixed-dim": "#ff7b6d",
        "secondary-dim": "#5f4e00",
        "on-error-container": "#570008",
        "on-tertiary-container": "#690003",
        "tertiary-dim": "#a40009",
        "on-secondary": "#fff2ce",
        "error-dim": "#9f0519",
        "surface-variant": "#dbdddd",
        "tertiary-container": "#ff9285",
        "surface-container": "#e7e8e8",
        tertiary: "#ba010c",
        "on-secondary-container": "#5a4a00",
        background: "#f6f6f6",
        "primary-container": "#5ea2ff",
        "primary-fixed-dim": "#4194fb",
        "primary-dim": "#004f98",
        "on-primary": "#eef2ff",
        "inverse-on-surface": "#9c9d9d",
        "secondary-fixed": "#fed400",
        secondary: "#6d5a00",
        "outline-variant": "#acadad",
        "on-primary-container": "#002348",
        "on-tertiary-fixed": "#3a0001",
        "on-primary-fixed-variant": "#002c59",
        "on-primary-fixed": "#000000",
        "surface-container-low": "#f0f1f1",
        error: "#b31b25",
        "surface-dim": "#d3d5d5",
        "surface-container-lowest": "#ffffff",
        "surface-tint": "#005bad",
        "green-accent": "#2ECC40",
      },
      fontFamily: {
        headline: ["Space Grotesk", "sans-serif"],
        body: ["Inter", "sans-serif"],
        label: ["Space Grotesk", "sans-serif"],
        mono: ["JetBrains Mono", "monospace"],
      },
      borderRadius: {
        DEFAULT: "0px",
        sm: "0px",
        md: "0px",
        lg: "0px",
        xl: "0px",
        "2xl": "0px",
        full: "9999px",
      },
      boxShadow: {
        neobrutal: "4px 4px 0px 0px #000000",
        "neobrutal-lg": "8px 8px 0px 0px #000000",
        "neobrutal-xl": "12px 12px 0px 0px #000000",
        "neobrutal-sidebar": "4px 0px 0px 0px #000000",
      },
    },
  },
  plugins: [],
};

export default config;
